document.writeln("<div class=\'header_bg\'>");
document.writeln("			<div id=\'header\'>");
document.writeln("		        <div id=\'header_con\'>");
document.writeln("		        	<p>欢迎来到中国汉语言教育网！</p>");
document.writeln("		        	<div class=\'header_right\'>");
document.writeln("		        		<div>");
document.writeln("			            	<a href=\'/HXCL/login\' id=\'blogin\'>登录</a>");
document.writeln("			            </div>");
document.writeln("			            <div>");
document.writeln("			            	<a href=\'/HXCL/register\' id=\'breg\'>注册</a>");
document.writeln("			            </div>");
document.writeln("		        	</div>");
document.writeln("		        	<div class=\'header_user\'>");
document.writeln("		        		<ul class=\'list-unstyled\'>");
document.writeln("							<li class=\'dropdown header_user_text\'>");
document.writeln("								<a class=\'dropdown-toggle\' data-toggle=\'dropdown\' href=\'#\'>中国大陆&nbsp;<span class=\'caret\'></span></a>");
document.writeln("								<ul class=\'list-unstyled dropdown-menu\' role=\'menu\'>");
document.writeln("									<li>");
document.writeln("										<a href=\'#\'>越南</a>");
document.writeln("										<a href=\'#\'>泰国</a>");
document.writeln("										<a href=\'#\'>缅甸</a>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("							<li class=\'dropdown header_user_text\'>");
document.writeln("								<a class=\'dropdown-toggle\' data-toggle=\'dropdown\' href=\'#\'> <small id=\"username\"></small>&nbsp;<span class=\'caret\'></span></a>");
document.writeln("								<ul class=\'list-unstyled dropdown-menu\' role=\'menu\'>");
document.writeln("									<li>");
document.writeln("										<a href=\'learning_process\' >学习的课程</a>");
document.writeln("										<a href=\'collection_course\' >收藏的课程</a>");
document.writeln("										<a href=\'#\' >我的订单</a>");
document.writeln("										<a href=\'my_set_up\' >个人设置</a>");
document.writeln("										<a href=\'#\' class=\"userOutLogin\">退出登录</a>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("							<li class=\'dropdown header_user_text\'>");
document.writeln("								<a class=\'dropdown-toggle\' data-toggle=\'dropdown\' href=\'#\'>消息&nbsp;<span class=\'caret\'></span></a>");
document.writeln("								<ul class=\'list-unstyled dropdown-menu\' role=\'menu\'>");
document.writeln("									<li>");
document.writeln("										<a href=sysMessage>系统消息</a>");
document.writeln("										<a href=managerMessage>管理员消息</a>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("		        	</div>");
document.writeln("		        	<div class=\'clearfix\'></div>");
document.writeln("		        </div>");
document.writeln("		    </div>");
document.writeln("		    <div class=\'header_nav\'>");
document.writeln("		    	<div class=\'logo\'>");
document.writeln("		    		<a href=\'http://www.hengmu-edu.com/HXCL/index\'><img src=\'/HXCL/img/logo.png\' /></a>");
document.writeln("		    	</div>");
document.writeln("		    	<div class=\'nav\'>");
document.writeln("		    		<ul class=\'list-unstyled\'>");
document.writeln("		    			<li>");
document.writeln("		    				<a href=\'/HXCL/index\'>首页</a>");
document.writeln("		    			</li>");
document.writeln("		    			<li>");
document.writeln("		    				<a href=\'/HXCL/list_of_catalogues\'>课程列表</a>");
document.writeln("		    			</li>");
document.writeln("		    			<li>");
document.writeln("		    				<a href=\'/HXCL/learning_process\'>学习进度</a>");
document.writeln("		    			</li>");
document.writeln("		    			<li>");
document.writeln("		    				<a href=\'/HXCL/latest_information\'>最新资讯</a>");
document.writeln("		    			</li>");
document.writeln("		    			<li>");
document.writeln("		    				<a href=\'/HXCL/about_us\' id=\'aboutUs\'>关于我们</a>");
document.writeln("		    			</li>");
document.writeln("		    		</ul>"); 
document.writeln("		    	</div>");
document.writeln("		    	<div class=\'clearfix\'></div>");
document.writeln("		    </div>");
document.writeln("		</div>");